name: 🐞 Bug report
description: Create a report to help us improve
title: "[BUG] <title>"
labels: ["type: bug", "status: triage"]
body:
- type: checkboxes
  id: screening
  attributes:
    label: I'm Not a Dummy, So I've Checked These
    description: Please go through this checklist before sending the report.
    options:
    - label: It happens on multiple browsers (if site)
      required: false
    - label: I've cleared browser cache and restarted browser (if site)
      required: false
    - label: I've asked support in MSF.gg Discord before writing this
      required: true
    - label: I have searched the existing issues
      required: true
- type: checkboxes
  id: product
  attributes:
    label: Product
    description: Which product are you having problems with?
    options:
      - label: Site
      - label: Bot
- type: textarea
  id: current
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: true
- type: textarea
  id: expected
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  id: steps
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
  validations:
    required: false
- type: textarea
  id: environment
  attributes:
    label: Environment
    description: |
      Examples:
        - Device: [e.g. Desktop, iPhone 6]
        - OS: [e.g. Windows 10, iOS 8.1]
        - Browser [e.g. Stock browser, Safari]
        - Version [e.g. 22, 12.1.2]
    value: |
        - Device: 
        - OS: 
        - Browser: 
        - Version: 
    render: markdown
  validations:
    required: false
- type: textarea
  id: additional-info
  attributes:
    label: Anything else?
    description: |
      Screenshots? Links? References? Anything that will give us more context about the issue you are encountering!
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
