name: 💡 Feature Request
description: 	Suggest an idea
title: "[REQUEST]: <title>"
labels: ["type: feature-request", "status: triage"]
body:
  - type: checkboxes
    id: product
    attributes:
      label: Product
      description: Which product are suggesting an idea to?
      options:
        - label: Site
        - label: Bot
  - type: textarea
    id: request
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    id: additional-info
    attributes:
      label: Anything else?
      description: |
        Screenshots? Links? References? Anything that will give us more context about the suggestion!

        Tip: You can attach images or other files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
