name: issue-automation

on:
  issues:
    types: [opened, reopened]

jobs:
  automate-issues-labels:
    runs-on: ubuntu-latest
    steps:
      - name: initial labeling
        uses: andymckay/labeler@master
        with:
          add-labels: "status: triage"
          ignore-if-labeled: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
