name: "issue-dev-reply"
on:
  issue_comment:
    types: [created]

jobs:
  issue_commented:
    runs-on: ubuntu-latest
    if: ${{ (github.event.comment.author_association == 'OWNER') || (github.event.comment.author_association == 'COLLABORATOR') }}
    steps:
      - name: labeling on dev reply
        uses: andymckay/labeler@master
        with:
          add-labels: "status: dev-reply"
          github-token: ${{ secrets.GITHUB_TOKEN }}
